FROM python:3.8

# install ubuntu packages.
# changes the source list in place to use archive.debian.org versions of the packages
# because the debian buster packages are no longer available at the original location
RUN sed -i \
    -e 's/deb.debian.org/archive.debian.org/g' \
    -e 's|security.debian.org/debian-security|archive.debian.org/debian-security|g' \
    -e '/buster-updates/d' \
    /etc/apt/sources.list \
 && DEBIAN_FRONTEND=noninteractive apt-get update --fix-missing \
 && apt-get install -y \
    libxml2-dev \
    libxslt1-dev \
    libxmlsec1-dev \
 && apt-get clean \
 && apt-get autoremove

RUN mkdir /matchminerAPI
COPY ./requirements.txt /matchminerAPI/requirements.txt
WORKDIR /matchminerAPI

# add github host to known hosts since it's private repo
RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh pip install git+ssh://git@github.com/pughlab/ctims-matchminer-engine.git@dev

RUN pip install -r requirements.txt

# Hack to work around https://github.com/py-bson/bson/issues/82
RUN pip --no-input uninstall --yes bson
RUN pip --no-input uninstall --yes pymongo
RUN pip install 'pymongo==3.10'
