version: "3"
services:
  mm-api:
    container_name: mm-api
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        MM_API_TOKEN: ${MM_API_TOKEN}
    # When developing locally, disable auth. By default, API is configured
    # to work with Okta's SSO saml system.
    command: python pymm_run.py serve
    volumes:
      - .:/matchminerAPI
    ports:
      - "5000:5000"
    environment:
      - SECRETS_JSON=./secrets_json_prod.json
    networks:
      - my-network

networks:
  my-network:
    external: true
