version: "3"
services:
  mm-api:
    container_name: mm-api
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        MM_API_TOKEN: ${MM_API_TOKEN}
    # When developing locally, disable auth. By default, API is configured
    # to work with Okta's SSO saml system.
    command: python pymm_run.py serve
    volumes:
      - .:/matchminerAPI
    ports:
      - "5000:5000"
    environment:
      - SECRETS_JSON=./secrets_json_prod.json
    networks:
      - ctims-network

  mm_mongo_db:
    container_name: mm_mongo_db
    image: mongo:3.6.10
    restart: on-failure
    ports:
      - "27020:27017"
    networks:
      - ctims-network
    volumes:
      - mm-mongo-db:/data/db

  rabbitmq:
    container_name: ctims-rabbitmq
    image: rabbitmq:3-management
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ctims-network 

volumes:
  mm-mongo-db:

networks:
  ctims-network:
    external: true
