FROM python:3.10

# install ubuntu packages.
RUN DEBIAN_FRONTEND=noninteractive apt-get update --fix-missing && apt-get install -y \
    libxml2-dev \
    libxslt1-dev \
    libxmlsec1-dev \
 && apt-get clean \
 && apt-get autoremove

RUN mkdir /matchminerAPI
COPY ./requirements.txt /matchminerAPI/requirements.txt
WORKDIR /matchminerAPI

# add github host to known hosts since it's private repo
RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh pip install git+ssh://git@github.com/pughlab/ctims-matchminer-engine.git@dev

RUN pip install -r requirements.txt

# Force upgrade networkx for Python 3.10 compatibility (oncotreenx may install old version)
RUN pip install --upgrade 'networkx==2.6.3'

# Hack to work around https://github.com/py-bson/bson/issues/82
RUN pip --no-input uninstall --yes bson
RUN pip --no-input uninstall --yes pymongo
RUN pip install 'pymongo==3.10'
